package gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author vitha
 */
public class Main extends javax.swing.JFrame {

    private static Main main;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/App_Icon.png"));
        this.setIconImage(icon.getImage());

        loadPanel(new Login());
    }

    public void loadPanel(JPanel panel) {

        if (!panel.isShowing()) {
            panels.removeAll();
            panels.add(panel, BorderLayout.CENTER);
            FlatLaf.updateUI();
        }

    }

    public static synchronized Main getMain() {
        if (Main.main == null) {
            Main.main = new Main();
        }
        return Main.main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panels = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GlobeMed Healthcare Management System ");
        setPreferredSize(new java.awt.Dimension(630, 491));
        setResizable(false);

        panels.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panels, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panels, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main.getMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panels;
    // End of variables declaration//GEN-END:variables
}
